# Generated by Django 4.2.7 on 2023-12-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_description',
            field=models.TextField(blank=True, null=True, verbose_name='商品詳細の説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='金額'),
        ),
    ]
